
### DIRECTORY SETTINGS ###

data_folder: "~/Code/ffa-framework/data"         # Location of .csv files
csv_file: "Application_1.csv"                    # Name of .csv file in data_dir
report_folder: "~/Code/ffa-framework/reports"    # Path for generating reports

### EDA SETTINGS ###

alpha: 0.05                # Significance threshold for statistical tests
bbmk_repetitions: 10000    # Number of bootstrap samples in BB-MK test
window_length: 10          # Window length used to compute AMS variances
window_step: 5             # Window step used to compute AMS variances

### PLOT SETTINGS ###

show_trend: True   # Add a line between data points when generating plots

