
##########################
### DIRECTORY SETTINGS ###
##########################

# Location of .csv files
data_folder: "~/Code/ffa-framework/data"         

# Name of .csv files in data_dir. Set to null to run on all files in data_folder.
csv_files: null

# Path for generating reports
report_folder: "~/Code/ffa-framework/reports"    

####################
### EDA SETTINGS ###
####################

# Mode for running EDA (must be "preset", "automatic", or "manual")
mode: "automatic"

# Preset split points (only works with mode: "preset")
split_points: 
  - 1960
  - 2000

# Significance threshold for statistical tests
alpha: 0.05

# Number of bootstrap samples in BB-MK test
bbmk_repetitions: 10000    

# Window length used to compute AMS variances
window_length: 10          

# Window step used to compute AMS variances
window_step: 5             

#####################
### PLOT SETTINGS ###
#####################

# Add a line between data points when generating plots
show_trend: True

#######################
### REPORT SETTINGS ###
#######################

# Enable report generation 
generate_report: True   

# Set output format for reports
report_format: 
  - "html_document"
