# Directory containing CSV files
data_dir: "~/Code/ffa-framework/data"                 

# Name of CSV file within data_dir
csv_file: "Application_1.csv"                 

# Path for generating reports
report_dir: "~/Code/ffa-framework/reports"  

# Significance level for EDA
alpha: 0.05       

# Number of bootstrap samples in BB-MK test
bbmk_repetitions: 10000      

# Window length used to compute AMS variances
window_length: 10 

# Window step used to compute AMS variances
window_step: 5    

